### ISSUE TITLE
Get 'hls' reference

### ISSUE THREAD

**Issue by lvgg3271** [Peer5/videojs-contrib-hls.js#13]
Thanks for your working first.

The problem is How can i get a reference to hls?
I need to handle errors outside the videojs-contrib-hlsjs.js.

**Comment by shacharz** [comment]
You can listen to hls events since this [PR](https://github.com/Peer5/videojs-contrib-hls.js/pull/11)
check it against master, I haven't released it yet.

**Comment by lvgg3271** [comment]
And how about 'hls' reference?
And how to bind eventNames that triggered by 'tech' ?

**Comment by mrbar42** [comment]
fixed on latest version (>v3.0.0)

**Comment by spodlecki** [comment]
I've been messing around, trying to get your events to be triggered. I think I'm missing something obvious, how would I listen for `hlsManifestLoaded`

I've tried to do: `player.on('hlsManifestLoaded', fn)` but it is never triggered.

I can see, through the code, that you are triggering the events via the Tech, but I don't think that bubbles up to the player which is the constant API...

Any help appreciated! I did not see any documentation to access the `hls` object either. From the code, doesn't look like you can?

**Comment by leoafarias** [comment]
@spodlecki `player.tech_.on('hlsManifestLoaded', fn)`

**Comment by benvirus** [comment]
The best way is to offer the 'hls' reference through `player.tech_. sourceHandler_.hls`, so we can get more infornation and invoke some hls's method. For example, change the level through setting hls.currentLevel .
