### ISSUE TITLE
how to correctly setup with videojs 

### ISSUE THREAD

**Issue by muhammad-ammar** [Peer5/videojs-contrib-hls.js#14]
I am trying to setup/register `videojs-contrib-hls` with videojs like below but its not working, it says
`a is undefined`

`videojs.registerComponent('Hls', require('videojs-contrib-hls'));`

What is the correct way to setup videojs-contrib-hls with videojs using requirejs?

**Comment by mrbar42** [comment]
`videojs-contrib-hls` is a different library than this one.
please consult their [repository](https://github.com/videojs/videojs-contrib-hls)
