### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by jgubman** [Peer5/videojs-contrib-hls.js#2]
According to your README, this plugin replaces the official videojs/videojs-contrib-hls
According to them, that's not true: https://github.com/videojs/videojs-contrib-hls/issues/797

**Comment by gkatsev** [comment]
Heh, thanks. I just wrote #3 as well :D

**Comment by jgubman** [comment]
👍

**Comment by gkatsev** [comment]
Quoting what I said in #3 below:
> The README here says that it is replacing videojs-contrib-hls. But it is not replacing it. videojs-contrib-hls is still a live project that is being active worked on.
It would be nice if instead it just calls out that it is similar to videojs-contrib-hls.

**Comment by shacharz** [comment]
Sorry for the confusion, I tried to pass to the reader the notion that he doesn't need both on his page. He can replace the existing contrib-hls on his page if he wishes to. Willing to accept PRs / suggestions

**Comment by jgubman** [comment]
PR submitted

**Comment by jgubman** [comment]
Thanks!

**Comment by shacharz** [comment]
Thank you ;)
