### ISSUE TITLE
README is misleading in regards to association with videojs-contrib-hls

### ISSUE THREAD

**Issue by gkatsev** [Peer5/videojs-contrib-hls.js#3]
The README here says that it is replacing videojs-contrib-hls. But it is not replacing it. videojs-contrib-hls is still a live project that is being active worked on.
It would be nice if instead it just calls out that it is similar to videojs-contrib-hls.

Thanks.

**Comment by gkatsev** [comment]
Closing in favor of #2.

**Comment by whadar** [comment]
@gkatsev thanks for pointing this out. We had no intention to say videojs-contrib-hls is not active or needs replacement 😄

**Comment by gkatsev** [comment]
It happens :)
And it's sorted out now, thanks!
