### ISSUE TITLE
Why the name "videojs-contrib-hls.js"?

### ISSUE THREAD

**Issue by forbesjo** [Peer5/videojs-contrib-hls.js#6]
I was wondering why this project is called "videojs-contrib-hls.js", it doesn't seem to be related to the videojs-contrib-hls plugin and "contrib" is used to signify projects offered by the org (see grunt-contrib-\* for example)

**Comment by shacharz** [comment]
Was going after the videojs plugin naming convention. 
The additional .js was to follow the hls.js convention

**Comment by saarangsoltani** [comment]
From the npm naming guides:
 
*Don't put "js" or "node" in the name. It's assumed that it's js, since you're writing a package.json file, and you can specify the engine using the "engines" field. (See below.)*

See https://docs.npmjs.com/files/package.json
