### ISSUE TITLE
No audio in Chrome (Mac)

### ISSUE THREAD

**Issue by kprigel** [Peer5/videojs-contrib-hls.js#7]
Here are two versions of the same page, one using peer5/videojs-contrib-hls, which has no audio during playback in Chrome: 
https://statusrecap.com/test.html

And the other using only videojs-contrib-hls, which does have audio during playback:
https://statusrecap.com/

I am using your excellent library on another site currently under development that uses VideoJS 5 source elements, which will only work using the peer5 version of videojs-contrib-hls, but unfortunately it produces the same no audio result.

**Comment by shacharz** [comment]
Thanks for the feedback,
It's due to a bug in hls.js 5.x which was resolved in hls.js 6.x.
Once hls.js 6.x will be released we'll switch to that and the issue should be resolved.

**Comment by kprigel** [comment]
I resolved by updating the dependencies and building a new dist, which appears to work.  The changes are on my fork.

**Comment by shacharz** [comment]
Cool, can you pr to master?
I'll create an additional 5.x branch which will have the 5.x hls.js version

**Comment by shacharz** [comment]
Merged your pr, released a new version and republished to npm
